files:
  include: 'public/sass/**/*.s+(a|c)ss'
  ignore:
    - './public/sass/variables/_svg_data.scss'

rules:
  no-color-keywords: 0
  no-color-literals: 0
  no-ids: 0
  nesting-depth: 0
  class-name-format: 0
  mixin-name-format: 0
  variable-name-format: 0
  no-transition-all: 0
  no-important: 0
  no-duplicate-properties: 0
  no-vendor-prefixes: 0
  placeholder-in-extend: 0
  pseudo-element: 0
  no-qualifying-elements: 0
  leading-zero: 0
  property-sort-order: 0
  mixins-before-declarations: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
