trigger:
  branches:
    include:
      - main
pr:
  - main

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    steps:
      - task: Npm@1
        displayName: NPM Ci
        inputs:
          command: ci

      - task: Npm@1
        displayName: NPM Build
        inputs:
          command: custom
          customCommand: run build

      - task: Npm@1
        displayName: NPM test
        inputs:
          command: custom
          customCommand: run test
