trigger:
  branches:
    include:
      - deprecation
pr:
  - deprecation

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    displayName: NPM Ci
    inputs:
      command: ci

  - task: Npm@1
    displayName: NPM Build
    inputs:
      command: custom
      customCommand: run build

  - task: Npm@1
    displayName: NPM test
    inputs:
      command: custom
      customCommand: run test
