name: Evolene CI

on:
  push:
    branches:
      - main
      - fix/back-to-top-breaks-in-dev
      - deprecation
  pull_request:
    branches:
      - main
      - fix/back-to-top-breaks-in-dev
      - deprecation
    paths-ignore:
      - '*.md'
      - '*.png'
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          SLACK_CHANNELS: '#team-kth-webb-build'
          NPM_UPDATES_AVAILABLE: True
          BUILD_INFORMATION_OUTPUT_FILE: '/config/version.js'
          CXXFLAGS: '--std=c++14'
          BRANCHES_SAVE_STARTING_WITH: 'refs/heads/fix/back-to-top-breaks-in-dev'
          BRANCHES_TAG_AS_MAIN: 'True'
        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}
